//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Hagalaz.Game.Scripts.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Messages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Hagalaz.Game.Scripts.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempt to catch a fish..
        /// </summary>
        internal static string You_attempt_to_catch_a_fish {
            get {
                return ResourceManager.GetString("You_attempt_to_catch_a_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempt to catch a Lobster..
        /// </summary>
        internal static string You_attempt_to_catch_a_lobster {
            get {
                return ResourceManager.GetString("You_attempt_to_catch_a_lobster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t carry any more fish..
        /// </summary>
        internal static string You_cant_carry_any_more_fish {
            get {
                return ResourceManager.GetString("You_cant_carry_any_more_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cast out your line....
        /// </summary>
        internal static string You_cast_out_your_line {
            get {
                return ResourceManager.GetString("You_cast_out_your_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cast out your net....
        /// </summary>
        internal static string You_cast_out_your_net {
            get {
                return ResourceManager.GetString("You_cast_out_your_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You catch a shark!.
        /// </summary>
        internal static string You_catch_a_shark {
            get {
                return ResourceManager.GetString("You_catch_a_shark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You catch a {0}..
        /// </summary>
        internal static string You_catch_a_X {
            get {
                return ResourceManager.GetString("You_catch_a_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You catch some {0}..
        /// </summary>
        internal static string You_catch_some_X {
            get {
                return ResourceManager.GetString("You_catch_some_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a fishing level of {0} or higher to fish here..
        /// </summary>
        internal static string You_must_have_a_fishing_level_of_X_or_higher_to_fish_here {
            get {
                return ResourceManager.GetString("You_must_have_a_fishing_level_of_X_or_higher_to_fish_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a {0} in order to fish at this spot..
        /// </summary>
        internal static string You_need_a_X_in_order_to_fish_at_this_spot {
            get {
                return ResourceManager.GetString("You_need_a_X_in_order_to_fish_at_this_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have {0} in order to fish at this spot..
        /// </summary>
        internal static string You_need_X_in_order_to_fish_at_this_spot {
            get {
                return ResourceManager.GetString("You_need_X_in_order_to_fish_at_this_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You start Harpooning fish..
        /// </summary>
        internal static string You_start_harpooning_fish {
            get {
                return ResourceManager.GetString("You_start_harpooning_fish", resourceCulture);
            }
        }
    }
}
