//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hagalaz.Game.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hagalaz.Game.Resources.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space in your bank..
        /// </summary>
        public static string BankFull {
            get {
                return ResourceManager.GetString("BankFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player can&apos;t be added yet..
        /// </summary>
        public static string CantAddPlayer {
            get {
                return ResourceManager.GetString("CantAddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot talk, because you are muted..
        /// </summary>
        public static string CantTalkMuted {
            get {
                return ResourceManager.GetString("CantTalkMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone is already attacking you..
        /// </summary>
        public static string Combat_SomeoneAttacking {
            get {
                return ResourceManager.GetString("Combat_SomeoneAttacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in PvP zone to attack this target..
        /// </summary>
        public static string Combat_SourceNeedPvPZone {
            get {
                return ResourceManager.GetString("Combat_SourceNeedPvPZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone else is already fighting your opponent..
        /// </summary>
        public static string Combat_TargetAttacked {
            get {
                return ResourceManager.GetString("Combat_TargetAttacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to attack this target, it needs to be in a PvP zone..
        /// </summary>
        public static string Combat_VictimNeedPvPZone {
            get {
                return ResourceManager.GetString("Combat_VictimNeedPvPZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat_VictorKillMessage_.
        /// </summary>
        public static string Combat_VictorKillMessage {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a crushing blow, you defeat {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_0 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a humiliating defeat for {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_1 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} didn&apos;t stand a chance against you..
        /// </summary>
        public static string Combat_VictorKillMessage_2 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have defeated {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_3 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s all over for {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_4 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} regrets the day they met you in combat..
        /// </summary>
        public static string Combat_VictorKillMessage_5 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} falls before your might..
        /// </summary>
        public static string Combat_VictorKillMessage_6 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can anyone defeat you? Certainly not {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_7 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were clearly a better fighter than {0}..
        /// </summary>
        public static string Combat_VictorKillMessage_8 {
            get {
                return ResourceManager.GetString("Combat_VictorKillMessage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raarrrrrgggggghhhhhhh!.
        /// </summary>
        public static string DragonBattleAxeSpecial {
            get {
                return ResourceManager.GetString("DragonBattleAxeSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are horribly burned by the dragonfire!.
        /// </summary>
        public static string DragonFireBurned {
            get {
                return ResourceManager.GetString("DragonFireBurned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your protection managed to resist all of the dragonfire..
        /// </summary>
        public static string DragonFireFully {
            get {
                return ResourceManager.GetString("DragonFireFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resistance to dragonfire has run out..
        /// </summary>
        public static string DragonFirePotionEffect {
            get {
                return ResourceManager.GetString("DragonFirePotionEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resistance to dragonfire is about to run out..
        /// </summary>
        public static string DragonFirePotionEffectWarning {
            get {
                return ResourceManager.GetString("DragonFirePotionEffectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your prayers manage to resist some of the dragonfire..
        /// </summary>
        public static string DragonFirePrayer {
            get {
                return ResourceManager.GetString("DragonFirePrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You manage to resist some of the dragonfire..
        /// </summary>
        public static string DragonFireSome {
            get {
                return ResourceManager.GetString("DragonFireSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space in your familiars inventory..
        /// </summary>
        public static string FamiliarInventoryFull {
            get {
                return ResourceManager.GetString("FamiliarInventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been kicked from the chat channel..
        /// </summary>
        public static string FC_Kicked {
            get {
                return ResourceManager.GetString("FC_Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been frozen..
        /// </summary>
        public static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too late, it&apos;s already gone..
        /// </summary>
        public static string GroundItemGone {
            get {
                return ResourceManager.GetString("GroundItemGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been injured and can&apos;t use protection prayers!.
        /// </summary>
        public static string Injured {
            get {
                return ResourceManager.GetString("Injured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space in your inventory..
        /// </summary>
        public static string InventoryFull {
            get {
                return ResourceManager.GetString("InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A magical force prevents you from moving..
        /// </summary>
        public static string MagicalForceMovement {
            get {
                return ResourceManager.GetString("MagicalForceMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A magical force prevents you from teleporting..
        /// </summary>
        public static string MagicalForceTeleport {
            get {
                return ResourceManager.GetString("MagicalForceTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space in your money pouch..
        /// </summary>
        public static string MoneyPouchFull {
            get {
                return ResourceManager.GetString("MoneyPouchFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough special energy to perform this attack..
        /// </summary>
        public static string NotEnoughSpecialEnergy {
            get {
                return ResourceManager.GetString("NotEnoughSpecialEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough special move points to perform this attack..
        /// </summary>
        public static string NotEnoughSpecialMovePoints {
            get {
                return ResourceManager.GetString("NotEnoughSpecialMovePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing interesting happens..
        /// </summary>
        public static string NothingInterestingHappens {
            get {
                return ResourceManager.GetString("NothingInterestingHappens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You pick up the cannon base from the ground....
        /// </summary>
        public static string PickCannonUp {
            get {
                return ResourceManager.GetString("PickCannonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} does not exist..
        /// </summary>
        public static string PlayerXDoesNotExist {
            get {
                return ResourceManager.GetString("PlayerXDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been poisoned..
        /// </summary>
        public static string Poisoned {
            get {
                return ResourceManager.GetString("Poisoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The poison wore off..
        /// </summary>
        public static string PoisonWoreOff {
            get {
                return ResourceManager.GetString("PoisonWoreOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;col=FF4000&gt;Your ring of wealth shines more brightly!&lt;/col&gt;.
        /// </summary>
        public static string RingOfWealthEffect {
            get {
                return ResourceManager.GetString("RingOfWealthEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Option.
        /// </summary>
        public static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re stunned..
        /// </summary>
        public static string Stunned {
            get {
                return ResourceManager.GetString("Stunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been tele blocked..
        /// </summary>
        public static string TeleBlocked {
            get {
                return ResourceManager.GetString("TeleBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t reach that..
        /// </summary>
        public static string YouCantReachThat {
            get {
                return ResourceManager.GetString("YouCantReachThat", resourceCulture);
            }
        }
    }
}
