name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: '**/*.csproj'
      - name: Restore
        run: dotnet restore --configfile NuGet.config
      - name: Build
        run: dotnet build --no-restore --verbosity minimal
      - name: Test
        run: dotnet test --no-build --logger "trx" --results-directory TestResults
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults/*.trx
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: TestResults/*.trx

  webapp:
    if: ${{ false }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hagalaz.Web.App
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build webapp
        run: pnpm run build
