name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: dotnet restore --configfile NuGet.config --locked-mode

      - name: Build
        run: dotnet build --no-restore --verbosity minimal

      - name: Test
        run: dotnet test --no-build --no-restore -p:TestingPlatformCommandLineArguments="--report-trx --coverage --coverage-output-format cobertura"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: '**/TestResults/*.trx'

  webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hagalaz.Web.App
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build webapp
        run: pnpm run build
